version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: auto
  open-pull-requests-limit: 10
  groups:
    oclif:
      patterns:
        - "oclif"
        - "@oclif/*"
    prod-patch-deps:
      dependency-type: "production"
      update-types:
        - "patch"
      exclude-patterns:
        - "sigstore"
        - "@sigstore/*"
    dev-deps:
      dependency-type: "development"      
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: daily
  open-pull-requests-limit: 10
  groups:
    minor-patch:
      update-types:
        - "minor"
        - "patch"
