name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  lint-source:
    name: Lint/build code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: 20
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint:check
    - name: Run formatter
      run: npm run prettier:check
    - name: Run build
      run: npm run build

  run-tests:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
        platform:
          - os: ubuntu-latest
            shell: bash
            jest-cache: /tmp/jest
          - os: macos-latest
            shell: bash
            jest-cache: /tmp/jest
          - os: windows-latest
            shell: cmd
            jest-cache: C:\\Users\\runneradmin\\AppData\\Local\\Temp\\jest
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - name: Checkout source
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: Manage Jest cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ matrix.platform.jest-cache }}
        key: ${{ hashFiles('**/package-lock.json') }}
    - name: Update npm
      run: npm install -g npm@8
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test:ci -- --cacheDirectory ${{ matrix.platform.jest-cache }}
