name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  lint-source:
    name: Lint/build code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
    - name: Setup node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint:check
    - name: Run build
      run: npm run build

  run-tests:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.14.0
          - 16.x
          - 18.17.0
          - 18.x
          - 20.5.0
          - 20.x
        platform:
          - os: ubuntu-latest
            shell: bash
            jest-cache: /tmp/jest
          - os: macos-latest
            shell: bash
            jest-cache: /tmp/jest
          - os: windows-latest
            shell: cmd
            jest-cache: C:\\Users\\runneradmin\\AppData\\Local\\Temp\\jest
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
    - name: Setup node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: Manage Jest cache
      uses: actions/cache@v3
      with:
        path: ${{ matrix.platform.jest-cache }}
        key: ${{ hashFiles('**/package-lock.json') }}
    - name: Update npm
      run: npm install -g npm@8
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test:ci -- --cacheDirectory ${{ matrix.platform.jest-cache }}
