name: Backward compatibility

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  verify:
    name: Verify bundles
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
    - name: Setup node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v3
      with:
        node-version: 18
        cache: npm
    - name: Install CLI
      run: npm install -g @sigstore/cli
    - name: Verify bundles
      run: |
        for FILE in ./tests/bundles/*.sigstore; do
          echo "Verifying ${FILE}"
          sigstore verify $FILE
        done

