name: Backward compatibility

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  verify:
    name: Verify bundles
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3
    - name: Setup node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v3
      with:
        node-version: 18.17
        cache: npm
    - name: Install CLI
      run: npm install -g @sigstore/cli
    - name: Verify bundles
      run: |
        for FILE in ./tests/bundles/*.sigstore; do
          echo "Verifying ${FILE}"
          sigstore verify $FILE
        done

