name: Backward compatibility

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  verify:
    name: Verify bundles
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v3
    - name: Setup node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v3
      with:
        node-version: 18
        cache: npm
    - name: Install CLI
      run: npm install -g @sigstore/cli
    - name: Verify bundles
      run: |
        for FILE in ./tests/bundles/*.sigstore; do
          echo "Verifying ${FILE}"
          sigstore verify $FILE
        done

