name: "Conformance tests"

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
    - name: Setup node
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v3
      with:
        node-version: 18
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: npm run build
    - uses: sigstore/sigstore-conformance@7375951316d6b28d07f7406c01e1dc7de2a75ce7 # v0.0.10
      with:
        entrypoint: ${{ github.workspace }}/packages/conformance/bin/run
        xfail: "test_verify_with_trust_root"
