name: "Conformance tests"

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  conformance-production:
    name: Conformance Test (Production)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Setup node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 22
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: npm run build
    - uses: sigstore/sigstore-conformance@ee4de0e602873beed74cf9e49d5332529fe69bf6 # v0.0.11
      with:
        entrypoint: ${{ github.workspace }}/packages/conformance/bin/run
        xfail: "test_verify_with_trust_root"

  conformance-staging:
    name: Conformance Test (Staging)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Setup node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 22
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: npm run build
    - uses: sigstore/sigstore-conformance@ee4de0e602873beed74cf9e49d5332529fe69bf6 # v0.0.11
      with:
        entrypoint: ${{ github.workspace }}/packages/conformance/bin/run
        environment: staging
