name: "Conformance tests"

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3
    - name: Setup node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: npm run build
    - uses: sigstore/sigstore-conformance@00922385de455be5ec46288a947044aa44fb0981 # v0.0.8
      with:
        entrypoint: ${{ github.workspace }}/packages/conformance/bin/run
