name: Smoke test

on:
  push:
    branches: ['main']

jobs:
  sign-verify:
    name: Sign/Verify Artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
    - name: Setup node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: |
        npm run build
    - name: Create artifact to sign
      run: |
        echo -n "hello world" > artifact
    - name: Sign artifact
      run: |
        ./bin/sigstore.js attest artifact "text/plain" > bundle.sigstore
    - name: Verify bundle
      run: |
        ./bin/sigstore.js verify bundle.sigstore
    - name: Archive bundle
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: bundle
        path: bundle.sigstore

