name: Update TUF Seeds

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  update-tuf-seeds:
    runs-on: ubuntu-latest
    env:
      DEBUG: "tuf:*"
      TUF_MIRROR: https://tuf-repo-cdn.sigstore.dev
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
      - name: Get Targets
        run: |
          npx @tufjs/cli download --metadata-base-url ${TUF_MIRROR} --cache-path ${{ runner.temp }}/tuf --unsafe-root-download --target-name trusted_root.json
          npx @tufjs/cli download --metadata-base-url ${TUF_MIRROR} --cache-path ${{ runner.temp }}/tuf --unsafe-root-download --target-name registry.npmjs.org/keys.json
      - name: Assemble TUF Seeds
        env:
          TUF_CACHE: ${{ runner.temp }}/tuf
          TARGET_TRUSTED_ROOT: trusted_root.json
          TARGET_NPM_KEYS: registry.npmjs.org%2Fkeys.json
        run: |
          jq -n -c \
            --arg mirror "$TUF_MIRROR" \
            --arg root "$(cat ${TUF_CACHE}/root.json | base64 -w 0)" \
            --arg trusted_root_key "$TARGET_TRUSTED_ROOT" \
            --arg trusted_root_value "$(cat ${TUF_CACHE}/targets/${TARGET_TRUSTED_ROOT} | base64 -w 0)" \
            --arg npm_keys_key "$TARGET_NPM_KEYS" \
            --arg npm_keys_value "$(cat ${TUF_CACHE}/targets/${TARGET_NPM_KEYS} | base64 -w 0)" \
            '{($mirror):{"root.json":$root,"targets":{($trusted_root_key):$trusted_root_value,($npm_keys_key):$npm_keys_value}}}' \
            > packages/tuf/seeds.json
      - name: Status
        run: |
          git status
          cat packages/tuf/seeds.json
          man base64
